### ISSUE TITLE
resnet_biggan_deep seems not consist with BigGanDeep in the paper

### ISSUE THREAD

**Issue by RuiLiFeng** [google/compare_gan#34]
In line 260, resnet_biggan_deep.py, z already be set into tf.concat([z,y],1), while in line 285, when feed parameters to the resnet block, z is treated as the original latents code and y is repeatedly feed into the block, which means that the resnet block in fact get y twice. This seems inconsistent with the settings in the biggan paper.
![image](https://user-images.githubusercontent.com/33709183/63264424-a25b2300-c2bd-11e9-89b4-692cec1d3e82.png)
![image](https://user-images.githubusercontent.com/33709183/63264446-a8e99a80-c2bd-11e9-86af-93f51da6deea.png)
![image](https://user-images.githubusercontent.com/33709183/63264467-b6068980-c2bd-11e9-8024-68d985fe7b71.png)

**Comment by Marvin182** [comment]
In this case z and y are indeed the same but only one is used.
We pass around both for consistency with other architectures. Since the only the part in the ResNet block that uses uses z or y is the batch norm, you can configure any of the batch norms and the code should run. I don't think we have batch norm implementation that use both z and y.
